import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  poweredByHeader: false,
  compress: true,
  images: {
    formats: ["image/avif", "image/webp"],
    remotePatterns: [
      {
        protocol: "https",
        hostname: "images.unsplash.com",
      },
    ],
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Frame-Options", value: "SAMEORIGIN" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
        ],
      },
    ];
  },
  async redirects() {
    return [
      {
        source: "/:path*",
        has: [{ type: "host", value: "www.startinggatefinancial.com" }],
        destination: "https://startinggatefinancial.com/:path*",
        permanent: true,
      },
      // ── Route drift fix ────────────────────────────────────────
      { source: "/financing/:slug", destination: "/financing-options/:slug", permanent: true },
      { source: "/financing", destination: "/financing-options", permanent: true },

      // ── WP → Next.js application page redirects ───────────────
      { source: "/apply/app/fix-and-flip", destination: "/apply/fix-and-flip", permanent: true },
      { source: "/apply/app/loan-application", destination: "/apply/loan-application", permanent: true },
      { source: "/apply/app/equipment-finance", destination: "/apply/equipment-finance", permanent: true },

      // ── WP → Next.js migration: 130 redirects ─────────────────
      // Pages (39)
      { source: "/privacy-policy", destination: "/privacy", permanent: true },
      { source: "/terms-and-conditions", destination: "/terms", permanent: true },
      { source: "/apply-now", destination: "/apply", permanent: true },
      { source: "/about-us", destination: "/about", permanent: true },
      { source: "/contact-us", destination: "/contact", permanent: true },
      { source: "/home", destination: "/", permanent: true },
      { source: "/revision-homepage", destination: "/", permanent: true },
      { source: "/newsletter", destination: "/blog", permanent: true },

      { source: "/merchant-cash-advance", destination: "/financing-options/merchant-cash-advance", permanent: true },
      { source: "/business-lines-of-credit-term", destination: "/financing-options/business-loc-term-loans", permanent: true },
      { source: "/sba-loans", destination: "/financing-options/sba-financing", permanent: true },
      { source: "/rental-loans", destination: "/financing-options/dscr-rental-loans", permanent: true },
      { source: "/equipment-financing", destination: "/financing-options/equipment-financing", permanent: true },
      { source: "/commercial-real-estate-financing", destination: "/financing-options/commercial-real-estate", permanent: true },
      { source: "/fix-n-flip-loans", destination: "/financing-options/fix-and-flip", permanent: true },
      { source: "/franchise-financing", destination: "/financing-options/franchise-financing", permanent: true },
      { source: "/startup-financing", destination: "/financing-options/startup-financing", permanent: true },
      { source: "/accounts-receivable", destination: "/financing-options/accounts-receivable-financing", permanent: true },
      { source: "/stated-income-commercial-real-estate", destination: "/financing-options/commercial-real-estate", permanent: true },
      { source: "/purchase-order-financing", destination: "/financing-options/accounts-receivable-financing", permanent: true },
      { source: "/consumer-finance", destination: "/financing-options", permanent: true },
      { source: "/real-estate-investors", destination: "/financing-options/commercial-real-estate", permanent: true },
      { source: "/startups-and-franchisees", destination: "/financing-options/startup-financing", permanent: true },

      { source: "/dscr-calculator", destination: "/tools/dscr-calculator", permanent: true },
      { source: "/mca-calculator", destination: "/tools/mca-calculator", permanent: true },
      { source: "/fica-tip-credit-calculator", destination: "/tools/fica-tip-credit-calculator", permanent: true },
      { source: "/business-loan-calculator", destination: "/tools/business-loan-calculator", permanent: true },

      { source: "/healthcare", destination: "/industries/medical-healthcare", permanent: true },
      { source: "/oil-and-gas-industry", destination: "/industries/oil-gas-services", permanent: true },
      { source: "/food-and-beverage-industry", destination: "/industries/restaurants-food", permanent: true },
      { source: "/contractors", destination: "/industries/construction", permanent: true },

      { source: "/commercial-lending-partner-program", destination: "/partners", permanent: true },
      { source: "/become-a-partner", destination: "/partners", permanent: true },

      { source: "/fix-n-flip-quote", destination: "/apply", permanent: true },
      { source: "/fix-n-flip-application-form", destination: "/apply", permanent: true },
      { source: "/equipment-finance-application", destination: "/apply", permanent: true },
      { source: "/loan-application", destination: "/apply", permanent: true },

      { source: "/healthcare-financing", destination: "/industries/medical-healthcare", permanent: true },
      { source: "/unlocking-capital-for-business-expansion-strategies-and-funding-options-2", destination: "/financing-options", permanent: true },

      // Blog posts — fixed: broken MDX redirects now point to live equivalents
      { source: "/understanding-franchise-financing", destination: "/blog/franchise-financing-guide", permanent: true },
      { source: "/small-business-administration-sba-how-can-they-help-your-small-business-grow", destination: "/blog/sba-loan-approval-guide", permanent: true },
      { source: "/the-essential-guide-to-medical-equipment-financing", destination: "/blog/healthcare-medical-equipment-financing", permanent: true },
      { source: "/everything-you-need-to-know-about-merchant-financing", destination: "/blog/understanding-merchant-cash-advances", permanent: true },
      { source: "/federal-reserve-lowers-interest-rates-by-25-basis-points-what-it-means-for-economic-growth", destination: "/blog", permanent: true },
      { source: "/is-it-possible-to-secure-a-loan-for-office-supplies", destination: "/blog/equipment-financing-strategy", permanent: true },
      { source: "/tips-for-using-accounts-receivable-financing", destination: "/financing-options/accounts-receivable-financing", permanent: true },
      { source: "/sba-loan-requirements-2025-the-ultimate-guide-to-documents-eligibility-approval", destination: "/blog/sba-loan-approval-guide", permanent: true },
      { source: "/whats-the-best-way-to-finance-medical-equipment", destination: "/blog/healthcare-medical-equipment-financing", permanent: true },
      { source: "/how-to-keep-your-business-financially-healthy", destination: "/financing-options", permanent: true },
      { source: "/how-do-small-business-loans-work", destination: "/financing-options", permanent: true },
      { source: "/how-to-get-working-capital-without-sacrificing-your-business-equity", destination: "/financing-options/business-loc-term-loans", permanent: true },
      { source: "/the-benefits-of-getting-an-equipment-loan", destination: "/blog/equipment-financing-strategy", permanent: true },
      { source: "/dscr-loans-vs-traditional-mortgages", destination: "/financing-options/dscr-rental-loans", permanent: true },
      { source: "/the-best-kinds-of-financing-for-pediatric-and-medical-offices", destination: "/blog/healthcare-medical-equipment-financing", permanent: true },
      { source: "/how-to-start-your-veteran-owned-business", destination: "/blog/startup-financing-guide", permanent: true },
      { source: "/the-basics-of-commercial-real-estate-financing", destination: "/financing-options/commercial-real-estate", permanent: true },
      { source: "/commercial-real-estate-loans-explained-in-3-parts", destination: "/financing-options/commercial-real-estate", permanent: true },
      { source: "/how-to-have-a-plan-without-making-a-business-plan", destination: "/blog/startup-financing-guide", permanent: true },
      { source: "/the-pros-and-cons-of-invoice-factoring", destination: "/financing-options/accounts-receivable-financing", permanent: true },
      { source: "/smart-equipment-financing-strategies-to-help-you-save-money", destination: "/blog/equipment-financing-strategy", permanent: true },
      { source: "/equipment-financing-for-your-business", destination: "/blog/equipment-financing-strategy", permanent: true },
      { source: "/tips-for-writing-a-business-plan", destination: "/blog/startup-financing-guide", permanent: true },
      { source: "/how-to-finance-cloud-infrastructure-software-upgrades", destination: "/financing-options/equipment-financing", permanent: true },
      { source: "/the-smart-way-to-fund-your-inventory-and-expansion", destination: "/financing-options/accounts-receivable-financing", permanent: true },
      { source: "/advantages-of-using-alternative-lending-for-business-funding", destination: "/financing-options", permanent: true },
      { source: "/how-to-secure-trucking-business-loans-for-fleet-expansion", destination: "/industries/trucking-transportation", permanent: true },
      { source: "/understanding-debt-service-coverage-ratio-dscr", destination: "/financing-options/dscr-rental-loans", permanent: true },
      { source: "/protect-yourself-from-interest-rates-hikes-with-sba-504-loan", destination: "/blog/sba-loan-approval-guide", permanent: true },
      { source: "/what-is-a-business-line-of-credit-and-how-to-apply", destination: "/financing-options/business-loc-term-loans", permanent: true },
      { source: "/how-to-find-the-right-factoring-company", destination: "/financing-options/accounts-receivable-financing", permanent: true },
      { source: "/10-tips-to-reduce-business-expenses", destination: "/blog", permanent: true },
      { source: "/6-myths-about-equipment-financing-to-ignore", destination: "/blog/equipment-financing-strategy", permanent: true },
      { source: "/growing-your-business-in-2020", destination: "/blog", permanent: true },
      { source: "/the-difference-between-asset-based-lending-and-factoring", destination: "/blog/the-difference-between-asset-based-lending-and-factoring", permanent: true },
      { source: "/how-to-use-microsoft-excel-to-simplify-business-accounting", destination: "/blog", permanent: true },
      { source: "/cash-flow-explained-for-a-new-business-owner", destination: "/blog/startup-financing-guide", permanent: true },
      { source: "/average-mca-repayment-terms-explained", destination: "/blog/understanding-merchant-cash-advances", permanent: true },
      { source: "/hybrid-home-mortgage-options-2025-changes-benefits", destination: "/blog", permanent: true },
      { source: "/working-capital-loans-for-restaurants-managing-rising-food-costs", destination: "/blog/working-capital-loans-for-restaurants-managing-rising-food-costs", permanent: true },
      { source: "/fica-tip-credit-restaurants-tax-benefits", destination: "/blog/fica-tip-credit-guide", permanent: true },
      { source: "/creative-funding-paths-for-contractors-beyond-traditional-contractor-loans", destination: "/blog/construction-contractor-financing", permanent: true },
      { source: "/fica-tip-credit-hospitality-restaurants", destination: "/blog/fica-tip-credit-guide", permanent: true },
      { source: "/7-day-plan-to-fast-track-your-sba-loan", destination: "/blog/sba-loan-approval-guide", permanent: true },
      { source: "/how-real-estate-investors-leverage-equipment-financing", destination: "/blog/real-estate-investor-financing-guide", permanent: true },
      { source: "/the-real-cost-of-startup-loan", destination: "/blog/startup-financing-guide", permanent: true },
      { source: "/why-your-home-mortgage-fell-through-how-to-fix-it", destination: "/blog", permanent: true },
      { source: "/mca-calculator-find-your-true-borrowing-costs-free-tool", destination: "/tools/mca-calculator", permanent: true },
      { source: "/best-restaurant-financing-options-for-2025", destination: "/blog/restaurant-cash-flow-financing", permanent: true },
      { source: "/it-equipment-financing-lease-vs-buy-whats-best-for-your-business", destination: "/blog/equipment-financing-strategy", permanent: true },
      { source: "/top-medical-equipment-lenders-in-2025", destination: "/blog/healthcare-medical-equipment-financing", permanent: true },
      { source: "/rental-loan-calculator-estimate-your-investment-property-payments-roi-starting-gate-financial", destination: "/blog/real-estate-investor-financing-guide", permanent: true },
      { source: "/loan-myths-that-keep-entrepreneurs-stuck", destination: "/financing-options", permanent: true },
      { source: "/sba-504-and-sba-7a", destination: "/blog/sba-loan-approval-guide", permanent: true },
      { source: "/working-capital-loans-impact-on-small-business-survival", destination: "/blog/restaurant-cash-flow-financing", permanent: true },
      { source: "/how-to-fund-your-business-without-the-hassle", destination: "/financing-options", permanent: true },
      { source: "/hidden-roi-of-equipment-loans-boost-productivity", destination: "/blog/equipment-financing-strategy", permanent: true },
      { source: "/use-business-loans-to-assist-with-staffing-difficulties", destination: "/financing-options/business-loc-term-loans", permanent: true },
      { source: "/franchise-financing-hacks", destination: "/blog/franchise-financing-guide", permanent: true },
      { source: "/how-to-finance-rental-property-with-rental-loans", destination: "/blog/real-estate-investor-financing-guide", permanent: true },
      { source: "/understanding-cap-rate-and-cash-on-cash-return-for-commercial-property-investment", destination: "/financing-options/commercial-real-estate", permanent: true },
      { source: "/smarter-small-business-financing", destination: "/financing-options", permanent: true },
      { source: "/unlocking-capital-for-business-expansion-strategies-and-funding-options", destination: "/financing-options", permanent: true },
      { source: "/is-a-business-line-of-credit-right-for-you-signs-its-time-to-apply", destination: "/financing-options/business-loc-term-loans", permanent: true },
      { source: "/the-ultimate-guide-to-equipment-financing-for-small-businesses", destination: "/blog/equipment-financing-strategy", permanent: true },
      { source: "/saas-financing-solutions-fuel-your-subscription-business-growth", destination: "/financing-options/business-loc-term-loans", permanent: true },
      { source: "/fast-business-loans-vs-smart-funding-find-the-right-fit", destination: "/financing-options", permanent: true },
      { source: "/tips-to-help-improve-your-credit-score-for-sba-loan-approval", destination: "/blog/sba-loan-approval-guide", permanent: true },
      { source: "/how-to-fix-your-business-credit-score", destination: "/blog/sba-loan-approval-guide", permanent: true },
      { source: "/rental-property-investing-in-the-current-market-with-starting-gate", destination: "/blog/real-estate-investor-financing-guide", permanent: true },
      { source: "/quick-business-loans-how-to-apply-and-get-approved-fast", destination: "/financing-options/business-loc-term-loans", permanent: true },
      { source: "/sba-loan-application-timeline-the-real-timeline-from-application-to-funding", destination: "/blog/sba-loan-approval-guide", permanent: true },
      { source: "/home-mortgage-refinance-options-explained-rate-savings-guide", destination: "/blog", permanent: true },
      { source: "/three-ways-to-fund-your-home-improvement-project", destination: "/blog", permanent: true },
      { source: "/business-loan-calculator-plan-smart-repayments-starting-gate-financial", destination: "/tools/business-loan-calculator", permanent: true },
      { source: "/equipment-loan-calculator-solution", destination: "/tools/business-loan-calculator", permanent: true },
      { source: "/business-vs-personal-credit-loan-impact-decoded-starting-gate-financial", destination: "/blog/sba-loan-approval-guide", permanent: true },
      { source: "/how-rental-loans-help-you-build-a-real-estate-portfolio-faster-starting-gate-financial", destination: "/blog/real-estate-investor-financing-guide", permanent: true },
      { source: "/how-to-use-term-loans-for-small-business-growth", destination: "/financing-options/business-loc-term-loans", permanent: true },
      { source: "/business-startup-guide-steps-funding-launch-strategies-starting-gate-financial", destination: "/blog/startup-financing-guide", permanent: true },
      { source: "/navigating-sba-504-loans-key-benefits-eligibility-and-how-to-apply", destination: "/blog/sba-loan-approval-guide", permanent: true },
      { source: "/inventory-financing-beyond-retail-opportunities-for-wholesalers-distributors-importers", destination: "/financing-options/accounts-receivable-financing", permanent: true },
      { source: "/preparing-your-business-for-loan-approval-dcr-inventory-cash-flow-checklist", destination: "/blog/sba-loan-approval-guide", permanent: true },
      { source: "/the-hidden-costs-of-under-capitalization-why-waiting-to-finance-business-growth-can-backfire", destination: "/financing-options", permanent: true },
      { source: "/demystifying-fica-tip-credit-for-food-and-beverage-business-owners", destination: "/blog/fica-tip-credit-guide", permanent: true },
      { source: "/how-to-use-our-mca-calculator-to-decide-if-a-merchant-cash-advance-makes-sense", destination: "/blog/understanding-merchant-cash-advances", permanent: true },
      { source: "/business-loan-calculator-101-what-the-numbers-are-really-telling-you", destination: "/tools/business-loan-calculator", permanent: true },
      { source: "/how-inventory-financing-can-be-a-game-changer-for-seasonal-retailers", destination: "/financing-options/accounts-receivable-financing", permanent: true },
      { source: "/restaurant-financing-challenges-and-solutions", destination: "/blog/restaurant-cash-flow-financing", permanent: true },
    ];
  },
};

export default nextConfig;
